# Generated by Django 3.1.6 on 2021-06-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=12)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('grupo_rh', models.CharField(choices=[('RO', 'O+'), ('RA', 'A+'), ('RA2', 'A-'), ('RB', 'B+'), ('RB2', 'B-'), ('RAB', 'AB+'), ('RAB2', 'AB-'), ('RO2', 'O-')], max_length=10)),
            ],
        ),
    ]
