# Generated by Django 3.1.6 on 2021-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='antecedentes_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='antecedentes_medico',
            field=models.ManyToManyField(to='docente.antecedentes_medico'),
        ),
    ]
