# Generated by Django 3.1.6 on 2021-06-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_auto_20210606_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='id',
        ),
        migrations.AddField(
            model_name='docente',
            name='codigo',
            field=models.CharField(default=99, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
