# Generated by Django 3.1.6 on 2021-06-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acudiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='antecedentes_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumna',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('tipo_identificacion', models.CharField(choices=[('RE', 'Registro Civil'), ('TI', 'Tarjeta Identidad'), ('CE', 'Cedula')], max_length=12)),
                ('identificacion', models.IntegerField(null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino')], max_length=10)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('modalidad_matricula', models.CharField(choices=[('I', 'Interna'), ('E', 'Externa')], max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('grado', models.CharField(choices=[('TR', 'Transicion'), ('PR', 'Primero'), ('SE', 'Segundo'), ('TE', 'Tercero'), ('CUA', 'Cuarto A'), ('CUB', 'Cuarto B'), ('QUA', 'Quinto A'), ('QUB', 'Quinto B'), ('SEA', 'Sexto A'), ('SEB', 'Sexto B'), ('SPA', 'Septimo A'), ('SPB', 'Septimo B'), ('OCA', 'Octavo A'), ('OCB', 'Octavo B'), ('NOA', 'Noveno A'), ('NOB', 'Noveno B'), ('NOC', 'Noveno C'), ('DEA', 'Decimo A'), ('DEB', 'Decimo B'), ('DEC', 'Decimo C'), ('ONA', 'Once A'), ('ONB', 'Once B'), ('ONC', 'Once C')], max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('eps', models.CharField(max_length=20)),
                ('arl', models.CharField(max_length=20)),
                ('grupo_rh', models.CharField(choices=[('RO', 'O+'), ('RA', 'A+'), ('RA2', 'A-'), ('RB', 'B+'), ('RB2', 'B-'), ('RAB', 'AB+'), ('RAB2', 'AB-'), ('RO2', 'O-')], max_length=10)),
                ('hobby', models.CharField(choices=[('BA', 'Bailar'), ('CA', 'Cantar'), ('FU', 'Jugar Futbol'), ('BO', 'Jugar Boleybol'), ('BAS', 'Jugar Baloncesto'), ('AJ', 'Jugar Ajedrez'), ('CI', 'Ir Cine'), ('MU', 'Escuchar Musica'), ('PA', 'Patinar'), ('VI', 'Viajar'), ('LE', 'Leer'), ('DI', 'Dibujar'), ('OT', 'Otro')], max_length=20)),
                ('antecedentes_medico', models.ManyToManyField(to='alumna.antecedentes_medico')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acudiente.persona')),
            ],
        ),
    ]
